[package]
name = "sandbox"
version = "0.1.0"
authors = ["Samuel Eguino <samuel.eguino@believesol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.harmony_engine]
path = "../engine"
